-- Profile photos on free_accounts.
--
-- The photo is the buyer's face and is shown to door staff on ticket check-in
-- so they can verify the person scanning matches the person who bought.
-- Soft-nudge for regular ticket buyers, hard requirement for trial-pass
-- activation and paid-membership application (see app-level enforcement).
--
-- Storage: PRIVATE bucket `profile-photos`. Reads happen via short-lived
-- signed URLs generated by the door-scanner API. Never expose these photos
-- publicly — they are personal biometric data and only staff at scan time
-- + the owner should see them.

alter table public.free_accounts
  add column if not exists profile_photo_path text,
  add column if not exists profile_photo_uploaded_at timestamptz;

comment on column public.free_accounts.profile_photo_path is
  'Storage path (bucket-relative) inside private profile-photos bucket. NULL if the user has not uploaded a photo yet. Reads always go through a short-lived signed URL — never expose this path directly to the public.';

comment on column public.free_accounts.profile_photo_uploaded_at is
  'Timestamp of the last profile-photo upload. Used to invalidate cached signed URLs and to show "recently updated" affordances in the door-scanner UI.';

-- Create the private bucket if it does not already exist. `public=false`
-- means the storage.objects rows are only accessible via signed URLs or by
-- an authorized policy — no anonymous CDN reads.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'profile-photos',
  'profile-photos',
  false,
  5 * 1024 * 1024,               -- 5 MB per photo cap
  array['image/jpeg', 'image/png', 'image/webp', 'image/heic', 'image/heif']
)
on conflict (id) do update set
  public = false,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- Storage RLS.
--
-- Two access patterns:
--   1. The account OWNER uploads / replaces / reads their own photo. Rows
--      live under `<user_id>/<filename>` so ownership is derived from the
--      path prefix.
--   2. The server (service-role key) reads any photo to generate signed URLs
--      for door staff. Service role bypasses RLS entirely — no policy
--      needed for that path.
--
-- We deliberately do NOT give staff a broad SELECT policy: staff never touch
-- storage directly, they go through /api/tickets/scan which uses the service
-- role to mint a scoped signed URL for one photo at a time. This keeps the
-- blast radius small if a staff account is ever compromised.

do $$
begin
  -- Drop any legacy policies with these names so re-running the migration
  -- (dev loops, staging refreshes) is safe.
  drop policy if exists "profile_photos owner read" on storage.objects;
  drop policy if exists "profile_photos owner insert" on storage.objects;
  drop policy if exists "profile_photos owner update" on storage.objects;
  drop policy if exists "profile_photos owner delete" on storage.objects;
end $$;

create policy "profile_photos owner read"
  on storage.objects for select
  using (
    bucket_id = 'profile-photos'
    and auth.role() = 'authenticated'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

create policy "profile_photos owner insert"
  on storage.objects for insert
  with check (
    bucket_id = 'profile-photos'
    and auth.role() = 'authenticated'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

create policy "profile_photos owner update"
  on storage.objects for update
  using (
    bucket_id = 'profile-photos'
    and auth.role() = 'authenticated'
    and (storage.foldername(name))[1] = auth.uid()::text
  )
  with check (
    bucket_id = 'profile-photos'
    and auth.role() = 'authenticated'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

create policy "profile_photos owner delete"
  on storage.objects for delete
  using (
    bucket_id = 'profile-photos'
    and auth.role() = 'authenticated'
    and (storage.foldername(name))[1] = auth.uid()::text
  );
